services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  
    container_name: fastapi
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://192.168.40.105:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
