services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
