services:
  redis:
    image: redis:7
    container_name: ${REDIS_CONTAINER_NAME}
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly ${REDIS_APPENDONLY}
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
